### PR TITLE
fixes #35 - remove default priority

### LINKED ISSUE #35: Hook so no longer set priority field.
Upstream projects may need to know if a priority was manually adjusted or not. This will allow if it is set, for the project to leave it alone.

### PR DESCRIPTION
**Pull request by dcrissman**
Remove defaultPriority

### CODE REVIEW

**Comment by dcrissman** [comment]
Fixes: https://github.com/lightblue-platform/lightblue-esb-hook/issues/35

**Comment by dcrissman** [comment]
@paterczm or @jewzaam - This is ready for review

**Comment by jewzaam** [comment]
@dcrissman do you care that there are references to default priorities in unit test data still?

**Comment by dcrissman** [comment]
@jewzaam Fixed. Good catch. Yeah, if you see any more that I missed, please let me know.

**Pull request merged**
